### ISSUE TITLE
Update Z-Push to 2.2.8

### ISSUE THREAD

**Issue by fbartels** [clearos/zarafa-z-push#1]
Hi guys,

originally I wanted to open a pull request, but I was not able to figure out what kind of checksum is used in https://github.com/clearos/zarafa-z-push/blob/clear7/sources.download (not md5sum or sha1sum apparently). 

Z-Push is meanwhile available in version 2.2.8 http://z-push.org/z-push-2-2-8-final-released/

**Comment by pcbaldwin** [comment]
Hello,

The update was pushed to the testing repository.  You can install the update with:

  yum --enablerepo=clearos-updates-testing upgrade zarafa-z-push

Tracker reference: https://tracker.clearos.com/view.php?id=7421

**Comment by fbartels** [comment]
Hi Peter,

thanks for updating it. I am not a centos/clearos user, but part of the z-push project.
